FROM docker.io/rust:1-slim-bookworm

WORKDIR /app

# Install diesel_cli and postgresql dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install diesel_cli --no-default-features --features postgres

# Copy migrations directory
COPY migrations ./migrations
COPY diesel.toml ./

CMD ["diesel", "migration", "run"]
